<! Credentials3.inc                                           >
<! PHP Identity Management & Cascading Style Sheets           >
<! by Michael McLaughlin                                      >
<!                                                            >
<! This holds the connection credentials for part 3.          >
<?php
  // Connection variables.
  define('SCHEMA',"idmgmt3");
  define('PASSWD',"idmgmt3");
  define('TNS_ID',"localhost/xe");
?>
